name: Compile Release
on:
  push:
    tags:
      - '*'
    branches:
      - experimental

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: actions/cache@v5
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build CrossPoint (Xteink X4)
        run: pio run -e gh_release

      - name: Upload Artifacts (Xteink X4)
        uses: actions/upload-artifact@v4
        with:
          name: CrossPoint-XteinkX4-${{ github.ref_name }}
          path: |
            .pio/build/gh_release/bootloader.bin
            .pio/build/gh_release/firmware.bin
            .pio/build/gh_release/firmware.elf
            .pio/build/gh_release/firmware.map
            .pio/build/gh_release/partitions.bin

      - name: Build CrossPoint (M5 Paper S3)
        run: pio run -e m5stack-paper-s3

      - name: Upload Artifacts (M5 Paper S3)
        uses: actions/upload-artifact@v4
        with:
          name: CrossPoint-M5PaperS3-${{ github.ref_name }}
          path: |
            .pio/build/m5stack-paper-s3/bootloader.bin
            .pio/build/m5stack-paper-s3/firmware.bin
            .pio/build/m5stack-paper-s3/firmware.elf
            .pio/build/m5stack-paper-s3/firmware.map
            .pio/build/m5stack-paper-s3/partitions.bin
